name: "Build MKS-Klipad50 Image"
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        shell: bash
        run: |
          #mkdir -p armbian-mkspi/output/images ; echo abc > armbian-mkspi/output/images/testfile
          git clone https://github.com/torte71/armbian-mkspi && cd armbian-mkspi && git checkout dts-symbolic && ./compile.sh BOARD=mksklipad50 BRANCH=current RELEASE=bookworm BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=xz
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Armbian-unofficial-MKS-Klipad50
          path: ./armbian-mkspi/output/images/

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          #name: Armbian-unofficial-MKS-Klipad50
          path: .
      #- run: zip -r build.zip testpath
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Armbian-unofficial-MKS-Klipad50/*"

